executor: slurm
nolock: True
jobs: 300  # Have up to N jobs submitted at any given time
latency-wait: 30  # Wait N seconds for output files due to latency
retries: 0  # Retry jobs N times.
keep-going: True
# max-jobs-per-second: 5
max-status-checks-per-second: 5
default-resources:
  mem_mb: 32000
  slurm_partition: "short"
  slurm_account:  # Same as sbatch -A. Not all clusters use this.
  runtime: 60  # In minutes
